### ISSUE TITLE
angular-mentions/mention 404 (Not Found)

### ISSUE THREAD

**Issue by bhavyamanu** [dmacfarlane/angular-mentions#62]
Hi 

I just installed mentions (steps followed from the document) but i am getting the following error. Please anyone help me to resolve this..

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular-mentions/mention
	Error: XHR error (404 Not Found) loading http://localhost:3000/angular-mentions/mention
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/angular-mentions/mention as "angular-mentions/mention" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/angular-mentions/mention as "angular-mentions/mention" from http://localhost:3000/app/app.module.js

**Comment by dmacfarlane** [comment]
Not able to reproduce. It may be a configuration or tool version error.
